name: Generate and Publish HTML

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifiez le code du dépôt
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Configurez Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Installer les dépendances Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown

    # 4. Générer les pages HTML
    - name: Generate HTML Pages
      run: |
        python index.py

    # 5. Déployer sur GitHub Pages
    - name: Deploy to GitHub Pages
      uses: actions/upload-pages-artifact@v1

    - name: Deploy Pages
      uses: actions/deploy-pages@v1
