name: Generate and Publish HTML

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifiez le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Configurez Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # 3. Installer les dépendances Python
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Générer les pages HTML
    - name: Generate HTML Pages
      run: python index.py

    # 5. Préparer les fichiers pour GitHub Pages
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./output/ # Spécifiez le dossier où vos pages HTML sont générées

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # 6. Déployer sur GitHub Pages
    - name: Deploy Pages
      uses: actions/deploy-pages@v1
